### ISSUE TITLE
Deliverable 1

### ISSUE THREAD

**Issue by Riade2022** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-Riade2022#1]
![Screen Shot 2023-11-03 at 3 13 45 PM](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-Riade2022/assets/103775235/00364489-2604-4957-97b3-4f49c4d475a4)

**Comment by instructorc** [comment]
Deliverable met!
