### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by Riade2022** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-Riade2022#2]
![Deliverable 2](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-Riade2022/assets/103775235/c0cf31a8-f2e3-4bf2-8f17-ac8a9fe8649f)

**Comment by instructorc** [comment]
Deliverable met! Good work!
